<template><div><p>建表</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code><span class="token keyword">create</span> <span class="token keyword">table</span> Course<span class="token punctuation">(</span>
    CNo <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span> <span class="token operator">NOT</span> <span class="token boolean">NULL</span> <span class="token punctuation">,</span>
    CName <span class="token keyword">varchar</span><span class="token punctuation">(</span><span class="token number">50</span><span class="token punctuation">)</span> <span class="token operator">NOT</span> <span class="token boolean">NULL</span> <span class="token punctuation">,</span>
    Grade <span class="token keyword">ENUM</span><span class="token punctuation">(</span><span class="token string">'1'</span><span class="token punctuation">,</span><span class="token string">'1.5'</span><span class="token punctuation">,</span><span class="token string">'2'</span><span class="token punctuation">,</span><span class="token string">'2.5'</span><span class="token punctuation">,</span><span class="token string">'3'</span><span class="token punctuation">,</span><span class="token string">'3.5'</span><span class="token punctuation">,</span><span class="token string">'4'</span><span class="token punctuation">,</span><span class="token string">'4.5'</span><span class="token punctuation">,</span><span class="token string">'5'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    Term <span class="token keyword">int</span> <span class="token keyword">check</span> <span class="token punctuation">(</span> Term<span class="token operator">></span><span class="token number">0</span> <span class="token operator">and</span> Term <span class="token operator">&lt;</span><span class="token number">9</span> <span class="token punctuation">)</span><span class="token punctuation">,</span>
    TNo <span class="token keyword">char</span><span class="token punctuation">(</span><span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    DepID <span class="token keyword">int</span> <span class="token operator">NOT</span> <span class="token boolean">NULL</span> 
    <span class="token keyword">FOREIGN</span> <span class="token keyword">KEY</span> <span class="token punctuation">(</span>TNo<span class="token punctuation">)</span> <span class="token keyword">REFERENCES</span> Teacher<span class="token punctuation">(</span>TNo<span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">FOREIGN</span> <span class="token keyword">KEY</span> <span class="token punctuation">(</span>DepID<span class="token punctuation">)</span> <span class="token keyword">REFERENCES</span> Department<span class="token punctuation">(</span>DepID<span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


